- src/api/routes.py
este bloque de codigo nos permite traer a nuestra base de datos todos los juegos con sus respectivos ID's, 
en la linea 23 y 25 queda pendiente por agregar los nombres de la tabla Models correspondiente a nuestros  juegos y id,
> agregar libreria requests y crear endpoint para traer todos los datos de los juegos a nuestra base de datos

- src/api/models.py
- src/api/routes.py
- src/api/utils.py
endpoint que hace peticion a la API de OpenAI y nos devulve el ID de 5 juegos
> 1.0 endpoint recomendations

- src/front/js/component/GameSuggestor.jsx
- src/front/js/pages/home.js
- src/front/styles/Gamesuggestor.css
Landing page finished waiting lisandro to do the fetch.
> Game suggestor card finished

- src/front/js/component/Footer.jsx
- src/front/styles/Footer.css
- src/front/styles/Gamesuggestor.css
- src/front/styles/index.css
Footer added
@media erased in gamesuggestor.css
> Footer done

- src/front/js/component/Footer.jsx
Footer anchor has been fixed. Now works.
> Footer 1.1

- src/front/js/component/GameSuggestor.jsx
- src/front/js/store/flux.js
complete functionality:
- adding getSuggestions function into flux.js file
- adding getGameDetails function into flux.js file
- setting input functionality.
> Get suggestions Functionality

- package.json
- src/front/js/component/Dropdown.jsx
- src/front/js/component/SignupForm.jsx
- src/front/js/store/flux.js
- src/front/styles/Dropdown.css
- useContext has been added and imported in dropdown.jsx, and the toggleDropdown variable has been modified to set the corresponding view if the registration is successful.
- In dropdown.jsx, the global state actions.setRegistrationSuccess(false) has also been applied to the handleSigninClick variable, and the button behavior has been modified to display "Sign In" once the registration is successful.
- In signupform.jsx, the global state from useContext has also been applied, the view has been changed from "profilecard" to "success". Duplicate comments have been removed, and the indentation in signupform.jsx has been improved.
- The registrationSuccess: false state has been added for registration success in flux.js. The setRegistrationSuccess function has been created in flux.js to set …
> Dropdown 1.5 update

- src/front/js/component/GameCard.jsx
- src/front/js/store/flux.js
- src/front/styles/gamecard.css
Added video highlights from the Steam API when hovering over the cards.
> Front-suggestions-1.5

- package-lock.json
- package.json
- src/front/js/component/GameSuggestor.jsx
- src/front/js/pages/suggestions.js
- src/front/js/store/flux.js
- src/front/styles/Gamesuggestor.css
- src/front/styles/gamecard.css
- Added scrolling text effect in the header of gamesuggestor.jsx using the Typed.js library.
- Fixed the 1px height and 100% width issue that caused a bug when the video was displayed in the recommendation card.
- Corrected the appId prop type error (string) in gamecard.jsx in suggestions.
- Added dependence of typed in package.json y package-lock.json
> Add Typed.js Scrolling Text Effect in Header, Fix CSS Bug and Prop Type Error

- src/api/routes.py
- src/front/js/component/GameCard.jsx
- src/front/js/pages/suggestions.js
- src/front/js/store/flux.js
fix show info fail data suggestions
> fix show info fail data suggestions

- src/api/routes.py
adding new endpoint (  /addfavouritegame/<int:app_id> )
> add favourite game endpoint

- src/front/js/component/GameCard.jsx
- src/front/js/component/GameSuggestor.jsx
- src/front/js/component/Loader.jsx
- src/front/js/component/ProfileCard.jsx
- src/front/js/component/SigninForm.jsx
- src/front/styles/loader.css
- Renamed class from `highlight` to `highlightedText` in the `span` for text effects in `gamesuggestor.jsx`.
- Removed duplicate `span` element in `gamesuggestor.jsx`.
- Fixed issue with input placeholder not disappearing when clicking on the input field.
- Added `loader.jsx` with corresponding class for handling fetch loading states.
> Refactor `gamesuggestor.jsx` and add loading component.

- src/front/js/component/Favorites.jsx
- src/front/js/component/GameCard.jsx
- src/front/js/component/Navbar.jsx
- src/front/js/layout.js
- src/front/js/pages/favorite.js
- src/front/js/pages/suggestions.js
- src/front/js/store/flux.js
- src/front/styles/gamecard.css
gamecard con icono de favoritos falta desarrollar logica de favoritos
> Solucionando problemas

- src/api/routes.py
- src/front/js/store/flux.js
- fixing headers in function flux
> fix functions in flux and routes

- src/api/routes.py
- src/front/js/component/GameCard.jsx
- src/front/js/pages/suggestions.js
- src/front/js/store/flux.js
- Fixed duplicate key error in suggestions.jsx. Enhanced the prompt in routes.py to prevent duplicate app IDs and added a new prompt to request only one game.
- Moved Loader component to Suggestions.jsx for better loading state management. Updated Suggestions.jsx to handle parallel game data fetching, ensuring the Loader is displayed during data retrieval. Removed Loader from GameCard.jsx and adjusted rendering logic to properly display games once all data is loaded, including error and empty state scenarios.
- Refactored GameCard component to improve stability.
> Fix duplicate key error, improve data fetching and loading management

- src/api/routes.py
> Adding endpoint to delete favourite game

- src/front/js/component/GameSuggestor.jsx
- src/front/js/component/Navbar.jsx
- src/front/js/component/ThemeSwitcher.jsx
- src/front/js/layout.js
- src/front/js/pages/suggestions.js
- src/front/js/store/flux.js
- src/front/styles/dropdown.css
- src/front/styles/footer.css
- src/front/styles/gamesuggestor.css
- src/front/styles/global.css
- src/front/styles/index.css
- Fixed background loading issue by adding state to manage background image loading, ensuring the image is fully loaded before rendering.
- Added a search icon to the input field in `gamesuggestor.jsx`.
- Adjusted the font size of the navbar for better readability.
- Updated gradient colors in both the navbar and footer for a more modern look.
- Added `themeswitcher.jsx` component for future theme switching functionality.
> Visual-improvs

- src/front/js/pages/aboutus.js
- src/front/styles/aboutus.css
> layout about us page

- src/api/routes.py
- src/front/js/component/GameCard.jsx
- src/front/js/pages/suggestions.js
- src/front/js/store/flux.js
modificacion de gamecard y suggestions para que muestre favoritos mediante ID del usuario
> se modifico gamecard y suggestions para traer favoritos

- src/front/js/component/Dropdown.jsx
Fix errors on the profile card view in dropdown
> Fix view card profile from dropdown

- src/front/js/component/ProfileCard.jsx
- src/front/js/pages/favorite.js
- src/front/styles/profilecard.css
modificaciones en el profilecard
> cambio relacionado a profilecard

- src/front/js/pages/single.jsx
- src/front/js/pages/suggestions.jsx
- src/front/js/store/flux.jsx
- src/front/styles/single.css
- Added layout to single.jsx with design aligned with API data.
- Created single.css to style single.jsx.
- Added console.warn in flux for better debugging.
- Replaced `validGames` with `gamesResults` in suggestions component.
- Added validation to handle cases where the game may be null.
> Single-details

- src/front/js/pages/favorite.jsx
- src/front/js/pages/suggestions.jsx
display card layout in favourites correctly
> display card layout in favourites correctly

- src/front/js/component/ProfileCard.jsx
Fix items in profilecard, add favourites section as well, also translate text to spanish.
> Fix items in profilecard

- src/front/js/pages/single.jsx
- src/front/js/pages/suggestions.jsx
- src/front/styles/index.css
- src/front/styles/single.css
- Fixed logo display in navbar also.
> Visual improvementes in Signle.jsx

- src/front/js/component/Footer.jsx
- src/front/js/layout.jsx
- src/front/js/pages/Contact.jsx
- src/front/styles/contact.css
> formulario de contacto creado

- src/front/js/component/Footer.jsx
- src/front/js/layout.jsx
montando nuevamente el sobre mygameguru
> mostrando el page about
